title: Incident Reports
email: safety@trolleymuseum.org
description: "Incident Reports"
baseurl: ""
url: ""

theme: minima


fleet_cars:
  - name: "CT 1160"
    short_name: "1160"
  - name: "CT 303"
    short_name: "303"
  - name: "Nashua 38"
    short_name: "38"
  - name: "Boston 4387"
    short_name: "4387"
  - name: "Boston 5821"
    short_name: "5821"
  - name: "WV 639"
    short_name: "639"
  - name: "City Of Manchester"
    short_name: "CityOfManchester"

non_fleet_cars:
  - name: "Cleveland 1227"
    short_name: 1227
  - name: "Twin Cities 1267"
    short_name: 1267
  - name: "Montreal 2"
    short_name: 2
  - name: "Toronto 2890"
    short_name: 2890
  - name: "Locomotive 300"
    short_name: 300
  - name: "Biddeford 31"
    short_name: 31
  - name: "Line Car 4"
    short_name: 4
  - name: "Snow Plow 5106"
    short_name: 5106
  - name: "CT 838"
    short_name: 838

other_cars:
  - name: "Bobcat"
    short_name: bobcat
  - name: "Parts Warehouse Propane Forklift"
    short_name: propaneforklift
  - name: "Parts Warehouse Electric Forklift"
    short_name: electricforklift

incident_types:
  - "derailment"
  - "dewire"
  - "fell off the stool"
  - "loading passenger"
  - "person under car with pole still up"
  - "pole rope swinging around"
  - "rail bikes"
  - "switch incident"
  - "trip and fall"
  - "trucks went in two different directions"
  - "unloading passenger"
  - "work crew"

weather_conditions:
  "Sun": "☀️"
  "Cloud": "☁️"
  "Foggy": "🌁"
  "Cloud with Snow": "🌨️"
  "Cloud with Lightning and Rain": "⛈️"
  "Cloud with Lightning": "🌩️"
  "Cloud with Rain": "🌧️"
  "Sun Behind Cloud": "⛅"
  "Sun Behind Small Cloud": "🌤️"
  "Sun Behind Large Cloud": "🌥️"
  "Ice": "❄️"
  "Wet": "💧"
  "Sun Behind Rain Cloud": "🌦️"
  "Tornado": "🌪️"
  "Full Moon": "🌕"
  "Crescent Moon": "🌙"
  "New Moon": "🌑"
  "Wind": "🌬️"
  "Fallen Leaves": "🍂"

staff:
  - lastname: Katie
    firstname: Orlando
    email: director@trolleymuseum.org
    phone: 
  - lastname: Steve
    firstname: Berg
    email: operations@trolleymuseum.org
    phone: 
  - lastname: Dave
    firstname: Rogers
    email: restoration@trolleymuseum.org
    phone: 
  - lastname: Brian
    firstname: Tenaglia
    email: fleet@trolleymuseum.org
    phone: 


other_members:
  - lastname: Chuck
    firstname: Griffith
    email: 
    phone: 
  - lastname: Peter
    firstname: Wilson
    email: 
    phone: 
  - lastname: James
    firstname: Van Bokkelen
    email: 
    phone: 


operators:
  - lastname: Alexander
    firstname: Gerry
    email: gerardalexander500@gmail.com
    phone: 

  - lastname: Allen
    firstname: Duncan
    email: d2allen@ibigroup.com
    phone: 781-444-3271

  - lastname: Ames
    firstname: Stan
    email: stanamesjr@gmail.com
    phone: 

  - lastname: Aronovitch
    firstname: Chuck
    email: caronovitch@gmail.com
    phone: 

  - lastname: Bennett
    firstname: Jeff
    email: octr202@gmail.com
    phone: 978-760-4357

  - lastname: Bourgault
    firstname: Kyle
    email: kylr23@yahoo.com
    phone: 

  - lastname: Brosseau
    firstname: Bob
    email: bbrosseau@comcast.net
    phone: 

  - lastname: Cappers
    firstname: Steve
    email: scappers@aol.com
    phone: 207-283-3689

  - lastname: Carrier Sr.
    firstname: Doug
    email: mthaynes1@comcast.net
    phone: 

  - lastname: Carter
    firstname: Derek
    email: mthaynes1@comcast.net
    phone: 

  - lastname: Castendyk
    firstname: Cullen
    email: castenbrau@yahoo.com
    phone: 

  - lastname: Coots
    firstname: Richard
    email: cootsr@gmail.com
    phone: 

  - lastname: Cosgro
    firstname: Matt
    email: matt.cosgro@comcast.net
    phone: 603-882-9240

  - lastname: Cosgro
    firstname: Rich
    email: rcosgro@comcast.net
    phone: 603-882-9240

  - lastname: Crawford
    firstname: Bill
    email: crawfordwm@verizon.net
    phone: 781-581-0411

  - lastname: Curry
    firstname: Mike
    email: mtcurry1786@yahoo.com
    phone: 207-646-2633

  - lastname: Dandridge
    firstname: Jon
    email: jonathandandridge3@gmail.com
    phone: 

  - lastname: delaVega
    firstname: Mike
    email: scot151@me.com
    phone: 617-480-2625

  - lastname: Dresner
    firstname: Lew
    email: video84@aol.com
    phone: 516-564-4746

  - lastname: Drye
    firstname: Rob
    email: robert.c.drye@hitchcock.org
    phone: 603-675-9159

  - lastname: Engler
    firstname: Eric
    email: eengler.music@gmail.com
    phone: 

  - lastname: Frost
    firstname: Mike
    email: frosty2412@gmail.com
    phone: 

  - lastname: Gabriel
    firstname: Chester
    email: opencar31@yahoo.com
    phone: 

  - lastname: Gingell
    firstname: Rob
    email: ais_gill@yahoo.com
    phone: 828-488-6970

  - lastname: Glickman
    firstname: Todd
    email: radio88@radio88.net
    phone: 781-229-8810

  - lastname: Grady
    firstname: John
    email: mta53@comcast.net
    phone: 

  - lastname: Griffith
    firstname: Charles
    email: mta53@comcast.net
    phone: 

  - lastname: Harrje
    firstname: Gail
    email: gailharrje@comcast.net
    phone: 

  - lastname: Haskell
    firstname: Peter
    email: STM694@roadrunner.com
    phone: 

  - lastname: Hessler
    firstname: Fred
    email: fhessler@cheerful.com
    phone: 

  - lastname: Hooper
    firstname: Scott
    email: STM694@roadrunner.com
    phone: 

  - lastname: Hubner
    firstname: Devon
    email: devon@hubner.org
    phone: 603-313-6916

  - lastname: Jayne
    firstname: Allan
    email: ajaynejr@aol.com
    phone: 

  - lastname: Kirkpatrick
    firstname: Dana
    email: dakirkp146@verizon.net
    phone: 

  - lastname: Koellmer
    firstname: Jeff
    email: jckoellmer@gmail.com
    phone: 

  - lastname: Kornechuk
    firstname: Dave
    email: dcjakornechuk@gmail.com
    phone: 

  - lastname: Lane
    firstname: Richard
    email: rlane3803@aol.com
    phone: 

  - lastname: LaRoche
    firstname: Denise
    email: denisemlaroche@gmail.com
    phone: 

  - lastname: LaRoche
    firstname: Tom
    email: Tom.LaRoche@protonmail.com
    phone: 

  - lastname: Mallory
    firstname: Bill
    email: MalloryBill117@gmail.com
    phone: 

  - lastname: Marnik
    firstname: Bill
    email: billmarnik@yahoo.com
    phone: 

  - lastname: McGinley
    firstname: Terry
    email: mcginley94@roadrunner.com
    phone: 

  - lastname: McMahon
    firstname: Jay
    email: meraconductor@gmail.com
    phone: 

  - lastname: Mercurio
    firstname: John
    email: johnmercurio59@yahoo.com
    phone: 

  - lastname: Miller
    firstname: Chelsea
    email: bizchelsea@gmail.com
    phone: 

  - lastname: Miner
    firstname: Jon
    email: cp_n18@yahoo.com
    phone: 

  - lastname: Nawrocki
    firstname: Jim
    email: jim.ruth77@gmail.com
    phone: 

  - lastname: Newton
    firstname: Dave
    email: donewton959@gmail.com
    phone: 207-590-1154

  - lastname: Pascucci
    firstname: Rich
    email: rail.instructor@gmail.com
    phone: 781-608-2314

  - lastname: Perkins
    firstname: Bob
    email: bobbyjperkins31@gmail.com
    phone: 413-525-8419

  - lastname: Perkins
    firstname: Donna
    email: donnaperkins15@gmail.com
    phone: 

  - lastname: Rees
    firstname: Bill
    email: billrees18@gmail.com
    phone: 603-232-7793

  - lastname: Rogers
    firstname: Dave
    email: restoration@trolleymuseum.org
    phone: 603-424-1053

  - lastname: Ruddell
    firstname: Ron
    email: londonbridgetoys@verizon.net
    phone: 

  - lastname: Schantz
    firstname: Jim
    email: jschantz@verizon.net
    phone: 

  - lastname: Speer
    firstname: Tim
    email: napiform@gmail.com
    phone: 

  - lastname: Stephenson
    firstname: Don
    email: beeblebrox2@verizon.net
    phone: 

  - lastname: Sylvester
    firstname: Mark
    email: stmtrolleyguy@yahoo.com
    phone: 781-439-5199

  - lastname: Sylvester
    firstname: Paul
    email: sylvesp@yahoo.com
    phone: 781-944-2561

  - lastname: Taylor
    firstname: Keith
    email: iblskeith@roadrunner.com
    phone: 

  - lastname: Tenaglia
    firstname: Brian
    email: fleet@trolleymuseum.org
    phone: 978-777-0669

  - lastname: Tsihlis
    firstname: Phil
    email: philjt@townisp.com
    phone: 508-667-3358

  - lastname: Tucker
    firstname: Tom
    email: twtjlt98@aol.com
    phone: 978-688-1678

  - lastname: vanBokkelen
    firstname: James
    email: jbvb@jbvb.us
    phone: 

  - lastname: Vardaro
    firstname: Dan
    email: danvardaro10@gmail.com
    phone: 

  - lastname: Whiteman
    firstname: Jeremy
    email: jeremy@jeremywhiteman.com
    phone: 

  - lastname: Wilson
    firstname: Peter
    email: peterwilson@comcast.com
    phone: 

  - lastname: Wolf
    firstname: Rick
    email: jrwolf@roadrunner.com
    phone: 207-967-3606


track_locations:
  - name: "Talbott Park"
    code: "talbott-park"
  - name: "Gregoire's Crossing"
    code: "gregoires-crossing"
  - name: "Meserve's Crossing"
    code: "meserves-crossing"
  - name: "Yard Limit Sign"
    code: "yard-limit-sign"
  - name: "Seward Switch"
    code: "seward-switch"
  - name: "Walker Junction"
    code: "walker-junction"
  - name: "Farview Interior"
    code: "farview-interior"
  - name: "Farview Yard"
    code: "farview-yard"
  - name: "Central Interior"
    code: "central-interior"
  - name: "Central Yard"
    code: "central-yard"
  - name: "Highwood Interior"
    code: "highwood-interior"
  - name: "Highwood Yard"
    code: "highwood-yard"
  - name: "Riverside Interior"
    code: "riverside-interior"
  - name: "Riverside Yard"
    code: "riverside-yard"
  - name: "Riverside Crossing"
    code: "riverside-crossing"
  - name: "SOAC Track"
    code: "soac-track"
  - name: "Butler Grove Lead"
    code: "butler-grove-lead"
  - name: "South Boston Interior"
    code: "south-boston-interior"
  - name: "South Boston Yard"
    code: "south-boston-yard"
  - name: "Shop 2 Interior"
    code: "shop-2-interior"
  - name: "Shop 2 Yard"
    code: "shop-2-yard"
  - name: "Shop 2 Lead"
    code: "shop-2-lead"
  - name: "Shop 2 Derail"
    code: "shop-2-derail"
  - name: "McKay Crossing"
    code: "mckay-crossing"
  - name: "Doherty Switch"
    code: "doherty-switch"
  - name: "Morrison Hill Station"
    code: "morrison-hill-station"
  - name: "North Loop Switch"
    code: "north-loop-switch"
  - name: "Arundel Station"
    code: "arundel-station"
  - name: "South Loop (Double-Slip) Switch"
    code: "south-loop-(double-slip)-switch"
  - name: "Visitor's Center"
    code: "visitors-center"
  - name: "B17 Dwarf Signal"
    code: "b17-dwarf-signal"
  - name: "Shuttle Position"
    code: "shuttle-position"
  - name: "Well Switch"
    code: "well-switch"
  - name: "Shop 1 Interior"
    code: "shop-1-interior"
  - name: "Shop 1 Yard"
    code: "shop-1-yard"
  - name: "Shop 1 Lead"
    code: "shop-1-lead"
  - name: "Shop 1 Derail"
    code: "shop-1-derail"
  - name: "Display Track"
    code: "display-track"

