source "https://rubygems.org"
gem "jekyll", "~> 4.3.3"
gem "minima", "~> 2.5"
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# jekyll 4.3.3
